# fly.toml app configuration file generated for hng-stage1-muddy-violet-2962 on 2024-07-04T12:13:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hng-stage1-muddy-violet-2962'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8089
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
